
FROM docker.io/exaile/gst-python:fedora31-python3
MAINTAINER Dustin Spicuzza <dustin@virtualroadside.com>

RUN true \
  && dnf -y install \
    python3-pytest \
    python3-mox3 \
    python3-sphinx \
    python3-sphinx_rtd_theme \
    findutils \
    make \
  && dnf clean all

