
FROM docker.io/exaile/gst-python:fedora31
MAINTAINER Dustin Spicuzza <dustin@virtualroadside.com>

RUN true \
  && dnf -y install \
    python2-pytest \
    python2-pip \
    findutils \
    make \
  && dnf clean all

RUN pip2 install sphinx mox3

RUN ln --symbolic /usr/bin/py.test-2 /usr/bin/py.test

