
FROM docker.io/exaile/gst-python:debian8
MAINTAINER Dustin Spicuzza <dustin@virtualroadside.com>

RUN true \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    python-pytest \
    python-mox3 \
    make \
  && rm -rf /var/lib/apt/lists/*
