
FROM docker.io/exaile/gst-python:fedora25
MAINTAINER Dustin Spicuzza <dustin@virtualroadside.com>

RUN true \
  && dnf -y install \
    python-pytest \
    python-mox3 \
    make \
  && dnf clean all
