
FROM docker.io/exaile/gst-python:debian9
MAINTAINER Dustin Spicuzza <dustin@virtualroadside.com>

RUN true \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    python-pytest \
    python-mox3 \
    python-pip \
    python-setuptools \
    python-wheel \
    make \
  && rm -rf /var/lib/apt/lists/* \
  && pip install -U pip setuptools wheel \
  && pip install sphinx sphinx-rtd-theme

