
FROM docker.io/exaile/gst-python:ubuntu16.04
MAINTAINER Dustin Spicuzza <dustin@virtualroadside.com>

RUN true \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
    python-pytest \
    python-mox3 \
    python-pip \
    python-setuptools \
    make \
  && rm -rf /var/lib/apt/lists/* \
  && pip install -U pip setuptools \
  && pip install sphinx

ENTRYPOINT []
CMD ["/bin/bash"]
