
FROM docker.io/exaile/gst-python:fedora26
MAINTAINER Dustin Spicuzza <dustin@virtualroadside.com>

RUN true \
  && dnf -y install \
    python2-pytest \
    python2-mox3 \
    python2-sphinx \
    findutils \
    make \
  && dnf clean all
